### ISSUE TITLE
Hibernate documentation site broken

### ISSUE THREAD

**Issue by ivanagui2** [hibernate/docs.hibernate.org#1]
Looks like all the documentation pages are damaged or not working. 
The below one is doc page 

https://hibernate.org/orm/documentation/5.6/

But most links are not working and redirect to redhat community spaces. 

https://spaces.redhat.com/hibernate/orm/5.6/quickstart/html_single/#all-updates

**Comment by sebersole** [comment]
Yep - https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user/topic/Documentation.20down

Been discussing with that team for weeks

**Comment by gsmet** [comment]
This is apparently fixed. You have to clean up your browser cache though.

**Comment by sebersole** [comment]
What is browser cache here?  Cookies?  History?  Something else?

**Comment by gsmet** [comment]
No, the cache itself (the pages the browser keeps in cache). The redirects were permanent so they can be kept in the cache.

I don't know which browser you use. In Firefox, it's in the history management but there is a specific Cache checkbox to clean it.

**Comment by sebersole** [comment]
So project links (e.g. https://docs.jboss.org/hibernate/orm) do not work.  Project-version links (e.g.  https://docs.jboss.org/hibernate/orm/6.0) do.  Not great, but better

**Comment by gsmet** [comment]
https://docs.jboss.org/hibernate/orm/ works for me.

**Comment by sebersole** [comment]
I cannot get that to re-direct me anywhere else.  It takes me to https://spaces.redhat.com/hibernate/orm/#all-updates

The version-specific ones work, so I can't imagine what other cached item it would have missed

**Comment by gsmet** [comment]
It looks like a cached redirect though. It's working from here and I never went there when the redirect was in place.

**Comment by sebersole** [comment]
I opened another browser and there https://docs.jboss.org/hibernate/orm/ did work.  So clearly something cached with the browser somewhere.
